# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

AWS_ACCESS_KEY_ID: AKIAI45WULOXZXAGOUJA
AWS_SECRET_ACCESS_KEY: 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
AWS_S3_BUCKET: achatesadvisors